spring:
  application:
    name: employee-service
  datasource:
    url: jdbc:h2:./employeeDb
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  port: 8585
